import { Match, Participant, Guess, RulePointConfig } from './types';

export const INITIAL_RULES: RulePointConfig = {
  exactScore: 10,
  winnerAndDiff: 7,
  winnerOnly: 5,
  oneTeamScore: 2,
  completeWrong: 0,
};

export const INITIAL_MATCHES: Match[] = [
  // ====== June 20-23 Finished matches (m_real_1 to m_real_5) ======
  {
    id: 'm_real_1',
    homeTeam: 'Turquia',
    awayTeam: 'Paraguai',
    homeFlag: '🇹🇷',
    awayFlag: '🇵🇾',
    homeScore: 0,
    awayScore: 1,
    status: 'finished',
    dateTime: '2026-06-20T18:00:00Z',
  },
  {
    id: 'm_real_2',
    homeTeam: 'Bélgica',
    awayTeam: 'Irã',
    homeFlag: '🇧🇪',
    awayFlag: '🇮🇷',
    homeScore: 0,
    awayScore: 0,
    status: 'finished',
    dateTime: '2026-06-21T19:00:00Z',
  },
  {
    id: 'm_real_3',
    homeTeam: 'Nova Zelândia',
    awayTeam: 'Egito',
    homeFlag: '🇳🇿',
    awayFlag: '🇪🇬',
    homeScore: 1,
    awayScore: 3,
    status: 'finished',
    dateTime: '2026-06-22T01:00:00Z',
  },
  {
    id: 'm_real_4',
    homeTeam: 'França',
    awayTeam: 'Iraque',
    homeFlag: '🇫🇷',
    awayFlag: '🇮🇶',
    homeScore: 3,
    awayScore: 0,
    status: 'finished',
    dateTime: '2026-06-22T21:00:00Z',
  },
  {
    id: 'm_real_5',
    homeTeam: 'Noruega',
    awayTeam: 'Senegal',
    homeFlag: '🇳🇴',
    awayFlag: '🇸🇳',
    homeScore: 3,
    awayScore: 2,
    status: 'finished',
    dateTime: '2026-06-23T00:00:00Z',
  },
  // ====== June 23 Round 1 Group K (m_real_6 and m_real_7) ======
  {
    id: 'm_real_6',
    homeTeam: 'Portugal',
    awayTeam: 'Uzbequistão',
    homeFlag: '🇵🇹',
    awayFlag: '🇺🇿',
    homeScore: 5,
    awayScore: 0,
    status: 'finished',
    dateTime: '2026-06-23T17:00:00Z',
  },
  {
    id: 'm_real_7',
    homeTeam: 'Colômbia',
    awayTeam: 'RD Congo',
    homeFlag: '🇨🇴',
    awayFlag: '🇨🇩',
    homeScore: 1,
    awayScore: 0,
    status: 'finished',
    dateTime: '2026-06-24T02:00:00Z',
  },
  // ====== June 24 Finished matches with guesses (m_real_18 to m_real_23) ======
  {
    id: 'm_real_18',
    homeTeam: 'Suíça',
    awayTeam: 'Canadá',
    homeFlag: '🇨🇭',
    awayFlag: '🇨🇦',
    homeScore: 2,
    awayScore: 1,
    status: 'finished',
    dateTime: '2026-06-24T19:00:00Z',
  },
  {
    id: 'm_real_19',
    homeTeam: 'Bósnia e Herzegovina',
    awayTeam: 'Catar',
    homeFlag: '🇧🇦',
    awayFlag: '🇶🇦',
    homeScore: 3,
    awayScore: 1,
    status: 'finished',
    dateTime: '2026-06-24T19:00:00Z',
  },
  {
    id: 'm_real_20',
    homeTeam: 'Escócia',
    awayTeam: 'Brasil',
    homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    awayFlag: '🇧🇷',
    homeScore: 0,
    awayScore: 3,
    status: 'finished',
    dateTime: '2026-06-24T22:00:00Z',
  },
  {
    id: 'm_real_21',
    homeTeam: 'Marrocos',
    awayTeam: 'Haiti',
    homeFlag: '🇲🇦',
    awayFlag: '🇭🇹',
    homeScore: 4,
    awayScore: 2,
    status: 'finished',
    dateTime: '2026-06-24T22:00:00Z',
  },
  {
    id: 'm_real_22',
    homeTeam: 'Tchéquia',
    awayTeam: 'México',
    homeFlag: '🇨🇿',
    awayFlag: '🇲🇽',
    homeScore: 0,
    awayScore: 3,
    status: 'finished',
    dateTime: '2026-06-25T01:00:00Z',
  },
  {
    id: 'm_real_23',
    homeTeam: 'África do Sul',
    awayTeam: 'Coreia do Sul',
    homeFlag: '🇿🇦',
    awayFlag: '🇰🇷',
    homeScore: 1,
    awayScore: 0,
    status: 'finished',
    dateTime: '2026-06-25T01:00:00Z',
  },
  // ====== June 25 Today's Scheduled matches (m_real_14 to m_real_17) ======
  {
    id: 'm_real_14',
    homeTeam: 'Equador',
    awayTeam: 'Alemanha',
    homeFlag: '🇪🇨',
    awayFlag: '🇩🇪',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-25T20:00:00Z',
  },
  {
    id: 'm_real_15',
    homeTeam: 'Curaçau',
    awayTeam: 'Costa do Marfim',
    homeFlag: '🇨🇼',
    awayFlag: '🇨🇮',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-25T20:00:00Z',
  },
  {
    id: 'm_real_16',
    homeTeam: 'Japão',
    awayTeam: 'Suécia',
    homeFlag: '🇯🇵',
    awayFlag: '🇸🇪',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-25T23:00:00Z',
  },
  {
    id: 'm_real_17',
    homeTeam: 'Tunísia',
    awayTeam: 'Países Baixos',
    homeFlag: '🇹🇳',
    awayFlag: '🇳🇱',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-26T02:00:00Z',
  },
  // ====== June 26 Tomorrow's Scheduled matches (m_real_26 to m_real_29) ======
  {
    id: 'm_real_26',
    homeTeam: 'Turquia',
    awayTeam: 'Estados Unidos',
    homeFlag: '🇹🇷',
    awayFlag: '🇺🇸',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-26T02:00:00Z',
  },
  {
    id: 'm_real_27',
    homeTeam: 'Paraguai',
    awayTeam: 'Austrália',
    homeFlag: '🇵🇾',
    awayFlag: '🇦🇺',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-26T02:00:00Z',
  },
  {
    id: 'm_real_28',
    homeTeam: 'Noruega',
    awayTeam: 'França',
    homeFlag: '🇳🇴',
    awayFlag: '🇫🇷',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-26T19:00:00Z',
  },
  {
    id: 'm_real_29',
    homeTeam: 'Senegal',
    awayTeam: 'Iraque',
    homeFlag: '🇸🇳',
    awayFlag: '🇮??',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-26T19:00:00Z',
  },
  // ====== June 27 Future Scheduled matches with guesses (m_real_24 and m_real_25) ======
  {
    id: 'm_real_24',
    homeTeam: 'Colômbia',
    awayTeam: 'Portugal',
    homeFlag: '🇨🇴',
    awayFlag: '🇵🇹',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T23:30:00Z',
  },
  {
    id: 'm_real_25',
    homeTeam: 'RD Congo',
    awayTeam: 'Uzbequistão',
    homeFlag: '🇨🇩',
    awayFlag: '🇺🇿',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T23:30:00Z',
  },
  {
    id: 'm_real_30',
    homeTeam: 'Cabo Verde',
    awayTeam: 'Arábia Saudita',
    homeFlag: '🇨🇻',
    awayFlag: '🇸🇦',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T00:00:00Z', // June 26 21:00 BRT
  },
  {
    id: 'm_real_31',
    homeTeam: 'Uruguai',
    awayTeam: 'Espanha',
    homeFlag: '🇺🇾',
    awayFlag: '🇪🇸',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T00:00:00Z', // June 26 21:00 BRT
  },
  {
    id: 'm_real_32',
    homeTeam: 'Egito',
    awayTeam: 'Irã',
    homeFlag: '🇪🇬',
    awayFlag: '🇮🇷',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T03:00:00Z', // June 27 00:00 BRT
  },
  {
    id: 'm_real_33',
    homeTeam: 'Nova Zelândia',
    awayTeam: 'Bélgica',
    homeFlag: '🇳🇿',
    awayFlag: '🇧🇪',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T03:00:00Z', // June 27 00:00 BRT
  },
  {
    id: 'm_real_34',
    homeTeam: 'Panamá',
    awayTeam: 'Inglaterra',
    homeFlag: '🇵🇦',
    awayFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T21:00:00Z', // June 27 18:00 BRT
  },
  {
    id: 'm_real_35',
    homeTeam: 'Croácia',
    awayTeam: 'Gana',
    homeFlag: '🇭🇷',
    awayFlag: '🇬🇭',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-27T21:00:00Z', // June 27 18:00 BRT
  },
  {
    id: 'm_real_36',
    homeTeam: 'Argélia',
    awayTeam: 'Áustria',
    homeFlag: '🇩🇿',
    awayFlag: '🇦🇹',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-28T02:00:00Z', // June 27 23:00 BRT
  },
  {
    id: 'm_real_37',
    homeTeam: 'Jordânia',
    awayTeam: 'Argentina',
    homeFlag: '🇯🇴',
    awayFlag: '🇦🇷',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
    dateTime: '2026-06-28T02:00:00Z', // June 27 23:00 BRT
  }
];

export const INITIAL_PARTICIPANTS: Participant[] = [];

export const INITIAL_GUESSES: Guess[] = [];

export const PREDEFINED_PARTICIPANTS: string[] = [
  "Aimee",
  "Angélica",
  "Carolina",
  "Eduardo (Boss)",
  "Eduardo (Log)",
  "Estevam",
  "Indianara",
  "Joelson",
  "João",
  "Lenon",
  "Olzênis",
  "Ricardo",
  "Robinson",
  "Rodrigo",
  "Rosinete",
  "Tais",
  "Taynara",
  "Uramar",
  "Valdir",
  "Yasmim"
];
